services:
  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=clean-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbData:/var/lib/postgresql/data
    ports:
      - 5455:5432

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
      
volumes:
  dbData:
    driver: local
