// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918142411_FixProxy")]
    partial class FixProxy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademyUser", b =>
                {
                    b.Property<Guid>("AcademiesId")
                        .HasColumnType("uuid")
                        .HasColumnName("academies_id");

                    b.Property<Guid>("AdministratorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrators_id");

                    b.HasKey("AcademiesId", "AdministratorsId")
                        .HasName("pk_academy_user");

                    b.HasIndex("AdministratorsId")
                        .HasDatabaseName("ix_academy_user_administrators_id");

                    b.ToTable("academy_user", "public");
                });

            modelBuilder.Entity("ClassCourseCourse", b =>
                {
                    b.Property<Guid>("ClassCoursesId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_courses_id");

                    b.Property<Guid>("CoursesId")
                        .HasColumnType("uuid")
                        .HasColumnName("courses_id");

                    b.HasKey("ClassCoursesId", "CoursesId")
                        .HasName("pk_class_course_course");

                    b.HasIndex("CoursesId")
                        .HasDatabaseName("ix_class_course_course_courses_id");

                    b.ToTable("class_course_course", "public");
                });

            modelBuilder.Entity("Domain.Academies.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LogoAttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_attachment_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_name");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_academies");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_academies_name");

                    b.HasIndex("TenantName")
                        .IsUnique()
                        .HasDatabaseName("ix_academies_tenant_name");

                    b.ToTable("academies", "public");
                });

            modelBuilder.Entity("Domain.Academies.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("NextClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_class_id");

                    b.Property<Guid?>("PreviousClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_class_id");

                    b.Property<int>("Section")
                        .HasColumnType("integer")
                        .HasColumnName("section");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("NextClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_next_class_id");

                    b.HasIndex("PreviousClassId")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_previous_class_id");

                    b.HasIndex("AcademyId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_academy_id_label");

                    b.HasIndex("AcademyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_academy_id_name");

                    b.ToTable("classes", "public");
                });

            modelBuilder.Entity("Domain.Academies.SchoolYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_school_years");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_school_years_academy_id");

                    b.ToTable("school_years", "public");
                });

            modelBuilder.Entity("Domain.Courses.ClassCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SchoolYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_year_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_class_courses");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_class_courses_academy_id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_class_courses_class_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_class_courses_school_year_id");

                    b.ToTable("class_courses", "public");
                });

            modelBuilder.Entity("Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.ToTable("courses", "public");
                });

            modelBuilder.Entity("Domain.Courses.CourseCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("CourseId1")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id1");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Credit")
                        .HasColumnType("double precision")
                        .HasColumnName("credit");

                    b.Property<Guid>("SchoolYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_year_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_course_credits");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_credits_course_id");

                    b.HasIndex("CourseId1")
                        .IsUnique()
                        .HasDatabaseName("ix_course_credits_course_id1");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_course_credits_school_year_id");

                    b.ToTable("course_credits", "public");
                });

            modelBuilder.Entity("Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrentClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_class_id");

                    b.Property<Guid>("CurrentSchoolYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_school_year_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_registration");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_registration_academy_id");

                    b.HasIndex("CurrentClassId")
                        .HasDatabaseName("ix_registration_current_class_id");

                    b.HasIndex("CurrentSchoolYearId")
                        .HasDatabaseName("ix_registration_current_school_year_id");

                    b.HasIndex("StudentId", "AcademyId", "CurrentSchoolYearId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_student_id_academy_id_current_school_year_id");

                    b.ToTable("registration", "public");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("birth_place");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_address");

                    b.Property<string>("CustomFields")
                        .HasColumnType("text")
                        .HasColumnName("custom_fields");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FatherContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_contact");

                    b.Property<string>("FatherJob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_job");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("MotherContact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_contact");

                    b.Property<string>("MotherJob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_job");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_name");

                    b.Property<string>("TutorContact")
                        .HasColumnType("text")
                        .HasColumnName("tutor_contact");

                    b.Property<string>("TutorName")
                        .HasColumnType("text")
                        .HasColumnName("tutor_name");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.ToTable("students", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("AcademyUser", b =>
                {
                    b.HasOne("Domain.Academies.Academy", null)
                        .WithMany()
                        .HasForeignKey("AcademiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academy_user_academies_academies_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AdministratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academy_user_users_administrators_id");
                });

            modelBuilder.Entity("ClassCourseCourse", b =>
                {
                    b.HasOne("Domain.Courses.ClassCourse", null)
                        .WithMany()
                        .HasForeignKey("ClassCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_course_course_class_courses_class_courses_id");

                    b.HasOne("Domain.Courses.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_course_course_courses_courses_id");
                });

            modelBuilder.Entity("Domain.Academies.Class", b =>
                {
                    b.HasOne("Domain.Academies.Academy", "Academy")
                        .WithMany("Classes")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classes_academies_academy_id");

                    b.HasOne("Domain.Academies.Class", "NextClass")
                        .WithOne()
                        .HasForeignKey("Domain.Academies.Class", "NextClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_classes_next_class_id");

                    b.HasOne("Domain.Academies.Class", "PreviousClass")
                        .WithOne()
                        .HasForeignKey("Domain.Academies.Class", "PreviousClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_classes_previous_class_id");

                    b.Navigation("Academy");

                    b.Navigation("NextClass");

                    b.Navigation("PreviousClass");
                });

            modelBuilder.Entity("Domain.Academies.SchoolYear", b =>
                {
                    b.HasOne("Domain.Academies.Academy", null)
                        .WithMany("SchoolYears")
                        .HasForeignKey("AcademyId")
                        .HasConstraintName("fk_school_years_academies_academy_id");
                });

            modelBuilder.Entity("Domain.Courses.ClassCourse", b =>
                {
                    b.HasOne("Domain.Academies.Academy", "Academy")
                        .WithMany()
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_courses_academies_academy_id");

                    b.HasOne("Domain.Academies.Class", "Class")
                        .WithMany("Courses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_courses_classes_class_id");

                    b.HasOne("Domain.Academies.SchoolYear", "SchoolYear")
                        .WithMany("ClassCourses")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_courses_school_years_school_year_id");

                    b.Navigation("Academy");

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Domain.Courses.CourseCredit", b =>
                {
                    b.HasOne("Domain.Courses.Course", "Course")
                        .WithMany("CourseCredits")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_credits_courses_course_id");

                    b.HasOne("Domain.Courses.Course", null)
                        .WithOne("CourseCredit")
                        .HasForeignKey("Domain.Courses.CourseCredit", "CourseId1")
                        .HasConstraintName("fk_course_credits_courses_course_id1");

                    b.HasOne("Domain.Academies.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_credits_school_years_school_year_id");

                    b.Navigation("Course");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("Domain.Registrations.Registration", b =>
                {
                    b.HasOne("Domain.Academies.Academy", "Academy")
                        .WithMany("Registrations")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_academies_academy_id");

                    b.HasOne("Domain.Academies.Class", "CurrentClass")
                        .WithMany("Registrations")
                        .HasForeignKey("CurrentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_classes_current_class_id");

                    b.HasOne("Domain.Academies.SchoolYear", "SchoolYear")
                        .WithMany("Registrations")
                        .HasForeignKey("CurrentSchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_school_years_current_school_year_id");

                    b.HasOne("Domain.Students.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_students_student_id");

                    b.Navigation("Academy");

                    b.Navigation("CurrentClass");

                    b.Navigation("SchoolYear");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Academies.Academy", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Registrations");

                    b.Navigation("SchoolYears");
                });

            modelBuilder.Entity("Domain.Academies.Class", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Domain.Academies.SchoolYear", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Domain.Courses.Course", b =>
                {
                    b.Navigation("CourseCredit");

                    b.Navigation("CourseCredits");
                });

            modelBuilder.Entity("Domain.Students.Student", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
