name: Deploy to Server

on:
  push:
    branches:
      - main  # change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/modern_academy
            git pull origin main
            cp -fp /var/secrets/appsettings.Development.json src/Web.Api/
            docker compose up web-api --build -d
